Repository pstpn/InTeam, pull requests merged in 2025-03, with the labels that each got.

#29 [#28]: Пофиксить корсы на бэке
  src/backend/cmd/main.go
  src/backend/config/config.yaml
  src/backend/go.mod
  src/backend/go.sum
  src/backend/pkg/http/middleware.go
Labels: be

#30 [#26]: Функционал покупателя на бэке
  .gitignore
  src/backend/cmd/main.go
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/go.mod
  src/backend/go.sum
  src/backend/internal/dto/user.go
  src/backend/internal/model/user.go
  src/backend/internal/router/handlers/errors.go
  src/backend/internal/router/handlers/handlers.go
  src/backend/internal/router/handlers/security.go
  src/backend/internal/router/ogen/oas_client_gen.go
  src/backend/internal/router/ogen/oas_handlers_gen.go
  src/backend/internal/router/ogen/oas_json_gen.go
  src/backend/internal/router/ogen/oas_operations_gen.go
  src/backend/internal/router/ogen/oas_parameters_gen.go
  src/backend/internal/router/ogen/oas_request_decoders_gen.go
  src/backend/internal/router/ogen/oas_request_encoders_gen.go
  src/backend/internal/router/ogen/oas_response_decoders_gen.go
  src/backend/internal/router/ogen/oas_response_encoders_gen.go
  src/backend/internal/router/ogen/oas_router_gen.go
  src/backend/internal/router/ogen/oas_schemas_gen.go
  src/backend/internal/router/ogen/oas_security_gen.go
  src/backend/internal/router/ogen/oas_server_gen.go
  src/backend/internal/router/ogen/oas_unimplemented_gen.go
  src/backend/internal/router/ogen/oas_validators_gen.go
  src/backend/internal/service/auth.go
  src/backend/internal/service/auth_test.go
  src/backend/internal/service/cart.go
  src/backend/internal/service/feedback.go
  src/backend/internal/service/order.go
  src/backend/internal/service/racket.go
  src/backend/internal/service/user.go
  src/backend/internal/storage/cart.go
  src/backend/internal/storage/feedback.go
  src/backend/internal/storage/order.go
  src/backend/internal/storage/postgres/cart.go
  src/backend/internal/storage/postgres/feedback.go
  src/backend/internal/storage/postgres/order.go
  src/backend/internal/storage/postgres/racket.go
  src/backend/internal/storage/postgres/user.go
  src/backend/internal/storage/racket.go
  src/backend/internal/storage/user.go
  src/backend/pkg/common/auth.go
  src/backend/pkg/common/copy.go
  src/backend/pkg/http/middleware.go
  src/backend/pkg/logger/logger.go
  src/backend/typespec/error.tsp
  src/backend/typespec/main.tsp
  src/backend/typespec/models.tsp
Labels: be

#34 [#25] Реализовать страницу регистрации
  .gitignore
  Makefile
  docker-compose.yml
  racket-shop/.gitignore
  racket-shop/Dockerfile
  racket-shop/README.md
  racket-shop/babel.config.js
  racket-shop/config.js
  racket-shop/jsconfig.json
  racket-shop/package.json
  racket-shop/public/favicon.ico
  racket-shop/public/index.html
  racket-shop/src/App.vue
  racket-shop/src/assets/admin.png
  racket-shop/src/assets/auth.png
  racket-shop/src/assets/auth_user.png
  racket-shop/src/assets/ball.png
  racket-shop/src/assets/cart.png
  racket-shop/src/assets/feedback.png
  racket-shop/src/assets/logo.png
  racket-shop/src/assets/order.png
  racket-shop/src/assets/racket.png
  racket-shop/src/assets/rackets.png
  racket-shop/src/assets/tool.png
  racket-shop/src/assets/unauth_user.png
  racket-shop/src/assets/users.png
  racket-shop/src/components/AppMenuBar.vue
  racket-shop/src/css/Buttons.css
  racket-shop/src/css/Colors.css
  racket-shop/src/css/Containers.css
  racket-shop/src/css/Fonts.css
  racket-shop/src/css/Forms.css
  racket-shop/src/css/Icons.css
  racket-shop/src/css/Input.css
  racket-shop/src/main.js
  racket-shop/src/router/index.js
  racket-shop/src/views/Auth/LoginView.vue
  racket-shop/src/views/Auth/RegisterView.vue
  racket-shop/src/views/User/ProfileView.vue
  racket-shop/vue.config.js
Labels: fe

#38 [#37]: Добавить парсинг пути к конфигу из envы
  src/backend/config/config.go
  src/backend/go.mod
  src/backend/go.sum
Labels: be

#42 [#31]: Функционал админа на бэке + #11 + #40 + #41
  src/backend/cmd/main.go
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/examples/client.go
  src/backend/go.mod
  src/backend/go.sum
  src/backend/internal/model/racket.go
  src/backend/internal/router/handlers/context.go
  src/backend/internal/router/handlers/errors.go
  src/backend/internal/router/handlers/handlers.go
  src/backend/internal/router/handlers/model.go
  src/backend/internal/router/handlers/security.go
  src/backend/internal/router/ogen/oas_client_gen.go
  src/backend/internal/router/ogen/oas_handlers_gen.go
  src/backend/internal/router/ogen/oas_json_gen.go
  src/backend/internal/router/ogen/oas_operations_gen.go
  src/backend/internal/router/ogen/oas_parameters_gen.go
  src/backend/internal/router/ogen/oas_request_decoders_gen.go
  src/backend/internal/router/ogen/oas_request_encoders_gen.go
  src/backend/internal/router/ogen/oas_response_decoders_gen.go
  src/backend/internal/router/ogen/oas_response_encoders_gen.go
  src/backend/internal/router/ogen/oas_router_gen.go
  src/backend/internal/router/ogen/oas_schemas_gen.go
  src/backend/internal/router/ogen/oas_server_gen.go
  src/backend/internal/router/ogen/oas_unimplemented_gen.go
  src/backend/internal/router/ogen/oas_validators_gen.go
  src/backend/internal/service/cart.go
  src/backend/pkg/common/auth.go
  src/backend/typespec/main.tsp
  src/backend/typespec/models.tsp
  src/backend/typespec/package.json
Labels: be

#39 [#27]: Функционал покупателя на фронте
  src/backend/pkg/http/middleware.go
  src/frontend/Makefile
  src/frontend/racket-shop/config.js
  src/frontend/racket-shop/package.json
  src/frontend/racket-shop/src/assets/ball.png
  src/frontend/racket-shop/src/assets/noview.png
  src/frontend/racket-shop/src/assets/view.png
  src/frontend/racket-shop/src/components/AppMenuBar.vue
  src/frontend/racket-shop/src/css/Buttons.css
  src/frontend/racket-shop/src/css/Containers.css
  src/frontend/racket-shop/src/css/Fonts.css
  src/frontend/racket-shop/src/css/Forms.css
  src/frontend/racket-shop/src/css/Grid.css
  src/frontend/racket-shop/src/css/Icons.css
  src/frontend/racket-shop/src/css/Modal.css
  src/frontend/racket-shop/src/main.js
  src/frontend/racket-shop/src/router/index.js
  src/frontend/racket-shop/src/views/Auth/LoginView.vue
  src/frontend/racket-shop/src/views/Auth/RegisterView.vue
  src/frontend/racket-shop/src/views/RacketsView.vue
  src/frontend/racket-shop/src/views/User/CartView.vue
  src/frontend/racket-shop/src/views/User/FeedbacksView.vue
  src/frontend/racket-shop/src/views/User/OrdersView.vue
  src/frontend/racket-shop/src/views/User/ProfileView.vue
Labels: fe

#45 [#12]: Интегрировать линтер
  src/backend/.golangci.yml
  src/backend/Makefile
  src/backend/cmd/main.go
  src/backend/config/config.go
  src/backend/config/config.local.yaml
  src/backend/config/config.prod.yaml
  src/backend/go.mod
  src/backend/go.sum
  src/backend/internal/dto/feedback.go
  src/backend/internal/dto/order.go
  src/backend/internal/model/order.go
  src/backend/internal/router/handlers/context.go
  src/backend/internal/router/handlers/errors.go
  src/backend/internal/router/handlers/handlers.go
  src/backend/internal/router/handlers/model.go
  src/backend/internal/router/handlers/security.go
  src/backend/internal/service/auth.go
  src/backend/internal/service/auth_test.go
  src/backend/internal/service/cart.go
  src/backend/internal/service/feedback.go
  src/backend/internal/service/order.go
  src/backend/internal/service/racket.go
  src/backend/internal/service/user.go
  src/backend/internal/storage/cart.go
  src/backend/internal/storage/feedback.go
  src/backend/internal/storage/order.go
  src/backend/internal/storage/postgres/cart.go
  src/backend/internal/storage/postgres/common.go
  src/backend/internal/storage/postgres/feedback.go
  src/backend/internal/storage/postgres/order.go
  src/backend/internal/storage/postgres/racket.go
  src/backend/internal/storage/postgres/user.go
  src/backend/internal/storage/racket.go
  src/backend/internal/storage/user.go
  src/backend/pkg/common/auth.go
  src/backend/pkg/common/copy.go
  src/backend/pkg/http/middleware.go
  src/backend/pkg/http/server.go
  src/backend/pkg/logger/logger.go
  src/backend/pkg/storage/postgres/core.go
  src/backend/pkg/storage/postgres/options.go
  src/backend/pkg/storage/postgres/pagination.go
Labels: be

#47 #15: add metrics collection
  src/backend/Makefile
  src/backend/cmd/main.go
  src/backend/config/config.go
  src/backend/config/config.local.yaml
  src/backend/config/config.prod.yaml
  src/backend/go.mod
  src/backend/go.sum
  src/backend/pkg/common/metrics.go
  src/backend/pkg/http/middleware.go
Labels: infra, be
