Repository pstpn/InTeam, pull requests merged in 2025-04, with the labels that each got.

#53 [#52]: Неправильный формат даты
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/internal/router/ogen/oas_json_gen.go
  src/backend/typespec/main.tsp
  src/backend/typespec/models.tsp
Labels: bug, be

#54 [#51]: Добавить имя пользователя в отзыве
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/internal/model/feedback.go
  src/backend/internal/router/handlers/handlers.go
  src/backend/internal/router/handlers/model.go
  src/backend/internal/router/ogen/oas_json_gen.go
  src/backend/internal/router/ogen/oas_schemas_gen.go
  src/backend/internal/service/feedback.go
  src/backend/internal/storage/feedback.go
  src/backend/internal/storage/postgres/common.go
  src/backend/internal/storage/postgres/feedback.go
  src/backend/typespec/main.tsp
  src/backend/typespec/models.tsp
Labels: feature, be

#55 [#50]: Профиль для админа
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/internal/router/handlers/handlers.go
  src/backend/internal/router/handlers/security.go
  src/backend/internal/router/ogen/oas_client_gen.go
  src/backend/internal/router/ogen/oas_handlers_gen.go
  src/backend/internal/router/ogen/oas_router_gen.go
  src/backend/internal/router/ogen/oas_server_gen.go
  src/backend/internal/router/ogen/oas_unimplemented_gen.go
  src/backend/typespec/main.tsp
Labels: feature, be

#57 [#56]: Добавить id для пользователей
  src/backend/docs/@typespec/openapi3/openapi.v1.yaml
  src/backend/internal/router/handlers/model.go
  src/backend/internal/router/ogen/oas_json_gen.go
  src/backend/internal/router/ogen/oas_schemas_gen.go
  src/backend/typespec/models.tsp
Labels: feature, be

#58 [hotfix]: fix server shutdown
  src/backend/cmd/main.go
  src/backend/pkg/http/server.go
Labels: bug, be

#64 [#61] : web fixes + #62
  src/frontend/racket-shop/src/components/AppMenuBar.vue
  src/frontend/racket-shop/src/css/Buttons.css
  src/frontend/racket-shop/src/css/Colors.css
  src/frontend/racket-shop/src/css/Containers.css
  src/frontend/racket-shop/src/css/Grid.css
  src/frontend/racket-shop/src/css/Icons.css
  src/frontend/racket-shop/src/css/Input.css
  src/frontend/racket-shop/src/css/Menu.css
  src/frontend/racket-shop/src/views/Admin/OrdersView.vue
  src/frontend/racket-shop/src/views/Admin/ProfileView.vue
  src/frontend/racket-shop/src/views/Admin/RacketsView.vue
  src/frontend/racket-shop/src/views/Admin/UsersView.vue
  src/frontend/racket-shop/src/views/RacketView.vue
  src/frontend/racket-shop/src/views/RacketsView.vue
  src/frontend/racket-shop/src/views/User/CartView.vue
  src/frontend/racket-shop/src/views/User/FeedbacksView.vue
  src/frontend/racket-shop/src/views/User/OrdersView.vue
  src/frontend/racket-shop/src/views/User/ProfileView.vue
Labels: bug, fe

#66 [*]: fixed confirm order
  src/frontend/racket-shop/src/views/User/CartView.vue
Labels: bug, fe
